app/blog/urls.py
from django.urls import path
from .views import category, blogs, blog_detail, add_comment #, category_python, category_django, category_laravel, category_mysql, category_vulnerabilidades

app_name = "appblog"

urlpatterns = [
    # path('', indexblog, name='blog'),
    path('blogs/', blogs, name='blogs'),
    path('blog-detail/<int:id>/<slug:slug>', blog_detail, name='blogdetail'),
    path('category/<int:id>', category, name='category'),
    path('add-comment/<int:id>', add_comment, name='addcomment'),

    # Views desativadas
    # path('category-python/', category_python, name='categorypython'),
    # path('category-django/', category_django, name='categorydjango'),
    # path('category-laravel/', category_laravel, name='categorylaravel'),
    # path('category-mysql/', category_mysql, name='categorymysql'),
    # path('category-vulnerabilidades/', category_vulnerabilidades, name='categoryvulnerabilidades'),

]

mvtec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView  # No Momento Fora de USO , estou usando o Include e não o TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.home.urls')), # página inicial
    path('blog/', include('app.blog.urls')),
    path('hora-extra/', include('app.hora_extra.urls')),
    # conforme solicitado no manual o CKEDITOR (GitHub CkEditor Django) adicionei essas linha
    path('ckeditor/', include('ckeditor_uploader.urls')),

]  # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # ESTOU USANDO DA FORMA QUE ESTA ABAIXO

if settings.DEBUG:
    # para funcionar os arquivos estaticos em DEBUG (Images, css, javascript, etc .)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">

<head>
    {% block meta %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="MVT" content="">
    {% endblock meta %}

    <title>
        {% block title %}
            MVTEC -
        {% endblock title %}
    </title>


    <!-- Custom fonts for this template-->
    <link href={% static "vendor/fontawesome-free/css/all.min.css" %} rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href={% static "/favicon.ico" %} rel="shortcut icon" type="favicon.ico">


    <!-- Custom styles for this template-->
    <link href={% static "css/sb-admin-2.min.css" %} rel="stylesheet">

    {% block css %}   {% endblock css %}

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gray-900 sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'home' %}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <!-- <i class="fas fa-laugh-wink"></i>-->
                    <img src={% static "img/LogoMVT_55x55.png" %} alt="http://127.0.0.1:8000" />
                </div>
                <!--<div class="sidebar-brand-text mx-3">MVTec</div>-->
            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">
                    <i class="fas fa-code"></i>
                     <span>MVTecnologia</span></a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
<!--                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"-->
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-book"></i>
                    <span>BLOG</span>
                </a>
<!--                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">-->

                <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Categorias:</h6>
                            <a class="collapse-item" href="{% url 'appblog:blogs' %}">TODAS</a>
                        {% for categoria in categorias_menu %}
                            <a class="collapse-item" href="{% url 'appblog:category' categoria.id %}">{{categoria}}</a>
                        {% endfor categoria %}
<!--                        <a class="collapse-item" href="{ url 'appblog:blogs' %}">TODAS</a> &lt;!&ndash;  Estou usando app_name na URL's por isso  passo primeiro o app_name e depois a viu blogs ex: "blog:blogs"   &ndash;&gt;-->
                    </div>
                </div>

<!--                <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionSidebar">-->
<!--                    <div class="bg-white py-2 collapse-inner rounded">-->
<!--                        <h6 class="collapse-header">Categorias:</h6>-->
<!--&lt;!&ndash;                        <a class="collapse-item" href="blogs">Todas</a> &lt;!&ndash;  Esse é um jeito de chamar  sem usar URL   &ndash;&gt;&ndash;&gt;-->
<!--                        <a class="collapse-item" href="{ url 'appblog:blogs' %}">TODAS</a> &lt;!&ndash;  Estou usando app_name na URL's por isso  passo primeiro o app_name e depois a viu blogs ex: "blog:blogs"   &ndash;&gt;-->
<!--                        <a class="collapse-item" href="{ url 'appblog:categorypython' %}">Python</a>-->
<!--                        <a class="collapse-item" href="{ url 'appblog:categorydjango' %}">Django</a>-->
<!--                        <a class="collapse-item" href="{ url 'appblog:categorylaravel' %}">Laravel</a>-->
<!--                        <a class="collapse-item" href="{ url 'appblog:categorymysql' %}">Mysql</a>-->
<!--                        <a class="collapse-item" href="{ url 'appblog:categoryvulnerabilidades' %}">Vulnerabilidades</a>-->
<!--&lt;!&ndash;                        <a class="collapse-item" href="{ url 'categoriasMenu' %}">TODAS</a>&ndash;&gt;-->

<!--                    </div>-->
<!--                </div>-->
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Aplicativos
            </div>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'hora_extra' %}">
                    <i class="fas fa-calculator"></i>
                    <span>Calcula Hora Extra Dia</span></a>
            </li>

            <!-- Nav Item - Tables -->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="tables.html">-->
<!--                    <i class="fas fa-fw fa-table"></i>-->
<!--                    <span>Tables</span></a>-->
<!--            </li>-->

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Contato
            </div>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">
                    <i class="fa fa-envelope-o"></i>
                    <span>Entrar em  Contato</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Heading -->
            <div class="sidebar-heading">
                Sobre
            </div>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'politica_privacidade' %}">
                    <i class="fa fa-unlock-alt"></i>
                    <span>Politícas de Privacidade</span></a>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'termos_uso' %}">
                    <i class="fa fa-stack-exchange"></i>
                    <span>Termos de Uso</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">


            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    {% block content %}
                    <!-- <h1 class="h3 mb-4 text-gray-800"></h1>-->
                    {% endblock content %}
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; MVT 2020</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
<!--    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"-->
<!--        aria-hidden="true">-->
<!--        <div class="modal-dialog" role="document">-->
<!--            <div class="modal-content">-->
<!--                <div class="modal-header">-->
<!--                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>-->
<!--                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">-->
<!--                        <span aria-hidden="true">×</span>-->
<!--                    </button>-->
<!--                </div>-->
<!--                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>-->
<!--                <div class="modal-footer">-->
<!--                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>-->
<!--                    <a class="btn btn-primary" href="login.html">Logout</a>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <!-- Bootstrap core JavaScript-->

    <script src={% static "vendor/jquery/jquery.min.js" %}></script>
    <script src={% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
    <!-- Core plugin JavaScript-->
    <script src={% static "vendor/jquery-easing/jquery.easing.min.js" %}></script>
    <!-- Custom scripts for all pages-->
    <script src={% static "js/sb-admin-2.min.js" %}></script>
    <!-- Custom scripts for all pages **** CAMPOS MASKS-->
    <script src={% static "js/staticfiles_js_jquery.mask.min.js" %}></script>
    <script src={% static "js/masks.js" %}></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-HXDX7Q0C6F"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-HXDX7Q0C6F');
    </script>
    {% block js %}{% endblock js %}

</body>

</html>